// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mysmemebqzhdxpxabuqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15c21lbWVicXpoZHhweGFidXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjUyMjgsImV4cCI6MjA3MTgwMTIyOH0.7sR2Atuy8-pbjM4hJEuuKlGoJoReiKEgs9EV-dUXKcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// URL where Supabase Edge Functions are hosted. Set VITE_SUPABASE_FUNCTIONS_URL in your .env if using functions.
export const SUPABASE_FUNCTIONS_URL = (import.meta.env.VITE_SUPABASE_FUNCTIONS_URL as string) || '';